-- Login-page requests to contact a school administrator.
-- Run this migration once in the Supabase SQL editor for an existing project.

-- Contact requests also create an item in the shared admin notification bell.
create table if not exists public.admin_notifications (
  id bigint generated by default as identity primary key,
  type text not null,
  student_id uuid not null references public.profiles(id) on delete cascade,
  changed_fields text[] not null default '{}',
  created_at timestamptz not null default now()
);

alter table public.admin_notifications
  drop constraint if exists admin_notifications_type_check;
alter table public.admin_notifications
  add constraint admin_notifications_type_check
  check (type in ('student_registration', 'student_profile_updated', 'admin_contact_requested', 'student_username_changed'));

create index if not exists admin_notifications_created_at_idx
  on public.admin_notifications (created_at desc);

alter table public.admin_notifications enable row level security;
drop policy if exists "admins read notifications" on public.admin_notifications;
create policy "admins read notifications" on public.admin_notifications
  for select to authenticated using (public.is_admin());

create table if not exists public.admin_contact_requests (
  id uuid primary key default gen_random_uuid(),
  profile_id uuid not null references public.profiles(id) on delete cascade,
  requester_email text not null,
  reason text not null default 'password_help' check (reason in ('username_help', 'password_help')),
  status text not null default 'open' check (status in ('open', 'resolved')),
  created_at timestamptz not null default now(),
  resolved_at timestamptz,
  resolved_by uuid references public.profiles(id) on delete set null
);

alter table public.admin_contact_requests
  drop constraint if exists admin_contact_requests_reason_check;
alter table public.admin_contact_requests
  add constraint admin_contact_requests_reason_check
  check (reason in ('username_help', 'password_help'));

create unique index if not exists admin_contact_requests_one_open_per_profile_idx
  on public.admin_contact_requests (profile_id)
  where status = 'open';

create index if not exists admin_contact_requests_status_created_idx
  on public.admin_contact_requests (status, created_at desc);

alter table public.admin_contact_requests enable row level security;

drop policy if exists "admins read contact requests" on public.admin_contact_requests;
create policy "admins read contact requests" on public.admin_contact_requests
  for select to authenticated using (public.is_admin());

-- The response is intentionally identical for known and unknown email addresses
-- so this public endpoint cannot be used to discover registered accounts.
-- Returns a status so the login page can tell a matching student whether they
-- already have an open concern, while keeping unknown emails indistinguishable
-- from newly-created requests.
drop function if exists public.request_admin_contact(text);
create or replace function public.request_admin_contact(submitted_email text, requested_reason text default 'password_help')
returns text
language plpgsql
security definer
set search_path = public, auth
as $$
declare
  normalized_email text := lower(trim(coalesce(submitted_email, '')));
  normalized_reason text := lower(trim(coalesce(requested_reason, '')));
  matched_profile_id uuid;
begin
  if normalized_reason not in ('username_help', 'password_help') then
    raise exception 'Choose username or password recovery';
  end if;
  if length(normalized_email) < 3 or length(normalized_email) > 320
     or normalized_email !~ '^[^[:space:]@]+@[^[:space:]@]+\.[^[:space:]@]+$' then
    raise exception 'Enter a valid email address';
  end if;

  select profile.id
  into matched_profile_id
  from auth.users account
  join public.profiles profile on profile.id = account.id
  where lower(account.email) = normalized_email
  limit 1;

  if matched_profile_id is null then
    return 'unknown';
  end if;

  insert into public.admin_contact_requests (profile_id, requester_email, reason)
  values (matched_profile_id, normalized_email, normalized_reason)
  on conflict (profile_id) where status = 'open' do nothing;

  if found then
    insert into public.admin_notifications (type, student_id, changed_fields)
    values ('admin_contact_requested', matched_profile_id, array[normalized_reason]);
    return 'created';
  else
    return 'existing';
  end if;
end;
$$;

create or replace function public.resolve_admin_contact_request(target_request_id uuid)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  if not public.is_admin() then
    raise exception 'Only administrators can resolve contact requests';
  end if;

  update public.admin_contact_requests
  set status = 'resolved', resolved_at = now(), resolved_by = auth.uid()
  where id = target_request_id and status = 'open';
end;
$$;

revoke all on function public.request_admin_contact(text, text) from public;
revoke all on function public.resolve_admin_contact_request(uuid) from public;
grant execute on function public.request_admin_contact(text, text) to anon, authenticated;
grant execute on function public.resolve_admin_contact_request(uuid) to authenticated;

do $$
begin
  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'admin_contact_requests'
  ) then
    alter publication supabase_realtime add table public.admin_contact_requests;
  end if;
end;
$$;
