-- Notify administrators whenever a student changes their own profile.
-- Run this migration once in the Supabase SQL editor for an existing project.

create table if not exists public.admin_notifications (
  id bigint generated by default as identity primary key,
  type text not null check (type in ('student_registration', 'student_profile_updated', 'admin_contact_requested')),
  student_id uuid not null references public.profiles(id) on delete cascade,
  changed_fields text[] not null default '{}',
  created_at timestamptz not null default now()
);

create index if not exists admin_notifications_created_at_idx
  on public.admin_notifications (created_at desc);

alter table public.admin_notifications enable row level security;

drop policy if exists "admins read notifications" on public.admin_notifications;
create policy "admins read notifications" on public.admin_notifications
  for select to authenticated using (public.is_admin());

create or replace function public.notify_admins_of_student_profile_update()
returns trigger
language plpgsql
security definer set search_path = public
as $$
declare
  fields text[];
begin
  if old.role = 'student' and auth.uid() = old.id then
    fields := array_remove(array[
      case when new.first_name is distinct from old.first_name then 'first name' end,
      case when new.last_name is distinct from old.last_name then 'last name' end,
      case when new.student_no is distinct from old.student_no then 'student number' end,
      case when new.grade_level is distinct from old.grade_level then 'grade level' end,
      case when new.shs_track is distinct from old.shs_track then 'SHS track' end,
      case when new.shs_strand is distinct from old.shs_strand then 'SHS strand' end,
      case when new.avatar_path is distinct from old.avatar_path then 'profile picture' end
    ], null);

    if cardinality(fields) > 0 then
      insert into public.admin_notifications (type, student_id, changed_fields)
      values ('student_profile_updated', old.id, fields);
    end if;
  end if;

  return new;
end;
$$;

drop trigger if exists profiles_notify_admins_after_student_update on public.profiles;
create trigger profiles_notify_admins_after_student_update
  after update on public.profiles
  for each row execute function public.notify_admins_of_student_profile_update();

create or replace function public.notify_admins_of_student_registration()
returns trigger
language plpgsql
security definer set search_path = public
as $$
begin
  if new.role = 'student' then
    insert into public.admin_notifications (type, student_id)
    values ('student_registration', new.id);
  end if;
  return new;
end;
$$;

drop trigger if exists profiles_notify_admins_after_student_insert on public.profiles;
create trigger profiles_notify_admins_after_student_insert
  after insert on public.profiles
  for each row execute function public.notify_admins_of_student_registration();

do $$
begin
  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'admin_notifications'
  ) then
    alter publication supabase_realtime add table public.admin_notifications;
  end if;
end;
$$;
