-- SkillMatchPH database schema
-- Run this file in the Supabase SQL Editor of a new project.
-- Authentication users live in Supabase's managed auth.users table.
-- To load the starter university catalog afterwards, run
-- supabase/seed_top_ph_universities.sql.

create table public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  first_name text not null,
  last_name text not null,
  student_no text not null unique,
  grade_level smallint not null check (grade_level in (11, 12)),
  shs_track text not null,
  shs_strand text not null,
  avatar_path text,
  username text not null unique check (username ~ '^[a-z0-9][a-z0-9._-]{2,29}$'),
  username_changed_at timestamptz,
  role text not null default 'student' check (role in ('student', 'admin')),
  status text not null default 'pending' check (status in ('pending', 'approved', 'rejected')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.programs (
  id uuid primary key default gen_random_uuid(),
  title text not null unique,
  category text not null check (category in (
    'Technology', 'Business', 'Engineering', 'Health',
    'Arts & Humanities', 'Sciences', 'Education'
  )),
  description text not null,
  icon_name text not null default 'BookOpen',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.universities (
  id uuid primary key default gen_random_uuid(),
  name text not null unique,
  location text,
  website text,
  logo_url text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- A university can offer many programs, and a program can be offered by many universities.
create table public.program_universities (
  program_id uuid not null references public.programs(id) on delete cascade,
  university_id uuid not null references public.universities(id) on delete cascade,
  primary key (program_id, university_id)
);

create table public.admin_contact_requests (
  id uuid primary key default gen_random_uuid(),
  profile_id uuid not null references public.profiles(id) on delete cascade,
  requester_email text not null,
  reason text not null default 'password_help' check (reason in ('password_help')),
  status text not null default 'open' check (status in ('open', 'resolved')),
  created_at timestamptz not null default now(),
  resolved_at timestamptz,
  resolved_by uuid references public.profiles(id) on delete set null
);

create table public.admin_notifications (
  id bigint generated by default as identity primary key,
  type text not null check (type in ('student_registration', 'student_profile_updated', 'admin_contact_requested', 'student_username_changed')),
  student_id uuid not null references public.profiles(id) on delete cascade,
  changed_fields text[] not null default '{}',
  created_at timestamptz not null default now()
);

create index profiles_role_status_idx on public.profiles (role, status);
create index program_universities_university_id_idx on public.program_universities (university_id);
create index admin_notifications_created_at_idx on public.admin_notifications (created_at desc);
create unique index admin_contact_requests_one_open_per_profile_idx
  on public.admin_contact_requests (profile_id) where status = 'open';
create index admin_contact_requests_status_created_idx
  on public.admin_contact_requests (status, created_at desc);

-- Keep timestamp columns accurate on edits.
create function public.set_updated_at()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create trigger profiles_set_updated_at before update on public.profiles
for each row execute function public.set_updated_at();

create trigger programs_set_updated_at before update on public.programs
for each row execute function public.set_updated_at();

create trigger universities_set_updated_at before update on public.universities
for each row execute function public.set_updated_at();

-- Every new Auth user receives a student profile. Role is deliberately hard-coded:
-- user-editable Auth metadata must never be allowed to create an administrator.
create function public.handle_new_user()
returns trigger
language plpgsql
security definer set search_path = public
as $$
declare
  provided_username text := nullif(lower(trim(new.raw_user_meta_data ->> 'username')), '');
  provided_student_no text := nullif(trim(new.raw_user_meta_data ->> 'student_no'), '');
begin
  if provided_username is not null and exists (
    select 1 from public.profiles where lower(username) = provided_username
  ) then
    raise exception 'That username is unavailable. Choose another username.';
  end if;

  if provided_student_no is not null and exists (
    select 1 from public.profiles where lower(student_no) = lower(provided_student_no)
  ) then
    raise exception 'That student number is already in use.';
  end if;

  insert into public.profiles (
    id, username, first_name, last_name, student_no, grade_level, shs_track, shs_strand, role, status
  ) values (
    new.id,
    provided_username,
    coalesce(new.raw_user_meta_data ->> 'first_name', ''),
    coalesce(new.raw_user_meta_data ->> 'last_name', ''),
    coalesce(provided_student_no, new.id::text),
    coalesce(nullif(new.raw_user_meta_data ->> 'grade_level', '')::smallint, 11),
    coalesce(new.raw_user_meta_data ->> 'shs_track', 'Academic'),
    coalesce(new.raw_user_meta_data ->> 'shs_strand', 'STEM'),
    'student',
    'pending'
  );
  return new;
end;
$$;

create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

-- Security helper. SECURITY DEFINER avoids circular RLS checks on profiles.
create function public.is_admin()
returns boolean
language sql
stable
security definer set search_path = public
as $$
  select exists (
    select 1 from public.profiles
    where id = auth.uid() and role = 'admin'
  );
$$;

alter table public.profiles enable row level security;
alter table public.admin_notifications enable row level security;
alter table public.admin_contact_requests enable row level security;
alter table public.programs enable row level security;
alter table public.universities enable row level security;
alter table public.program_universities enable row level security;

-- Students can view their own profile; admins can manage all profiles.
create policy "read own profile or all as admin" on public.profiles
  for select to authenticated using (id = auth.uid() or public.is_admin());
create policy "admin updates profiles" on public.profiles
  for update to authenticated using (public.is_admin()) with check (public.is_admin());
create policy "students update own profile" on public.profiles
  for update to authenticated
  using (id = auth.uid() and role = 'student')
  with check (id = auth.uid() and role = 'student');
create policy "admins read notifications" on public.admin_notifications
  for select to authenticated using (public.is_admin());
create policy "admins read contact requests" on public.admin_contact_requests
  for select to authenticated using (public.is_admin());

-- Self-service edits must never change authorization or approval fields.
create function public.protect_profile_system_fields()
returns trigger
language plpgsql
security definer set search_path = public
as $$
begin
  if not public.is_admin() then
    new.id := old.id;
    new.role := old.role;
    new.status := old.status;
    if current_setting('app.allow_username_change', true) is distinct from 'true' then
      new.username := old.username;
      new.username_changed_at := old.username_changed_at;
    end if;
    new.created_at := old.created_at;
  end if;
  return new;
end;
$$;

create trigger profiles_protect_system_fields before update on public.profiles
for each row execute function public.protect_profile_system_fields();

create function public.notify_admins_of_student_profile_update()
returns trigger
language plpgsql
security definer set search_path = public
as $$
declare
  fields text[];
begin
  if old.role = 'student' and auth.uid() = old.id then
    fields := array_remove(array[
      case when new.first_name is distinct from old.first_name then 'first name' end,
      case when new.last_name is distinct from old.last_name then 'last name' end,
      case when new.student_no is distinct from old.student_no then 'student number' end,
      case when new.grade_level is distinct from old.grade_level then 'grade level' end,
      case when new.shs_track is distinct from old.shs_track then 'SHS track' end,
      case when new.shs_strand is distinct from old.shs_strand then 'SHS strand' end,
      case when new.avatar_path is distinct from old.avatar_path then 'profile picture' end
    ], null);

    if cardinality(fields) > 0 then
      insert into public.admin_notifications (type, student_id, changed_fields)
      values ('student_profile_updated', old.id, fields);
    end if;
  end if;
  return new;
end;
$$;

create trigger profiles_notify_admins_after_student_update
  after update on public.profiles
  for each row execute function public.notify_admins_of_student_profile_update();

create function public.notify_admins_of_student_registration()
returns trigger
language plpgsql
security definer set search_path = public
as $$
begin
  if new.role = 'student' then
    insert into public.admin_notifications (type, student_id)
    values ('student_registration', new.id);
  end if;
  return new;
end;
$$;

create trigger profiles_notify_admins_after_student_insert
  after insert on public.profiles
  for each row execute function public.notify_admins_of_student_registration();

alter publication supabase_realtime add table public.admin_notifications;

-- Public avatar reads, with writes limited to the signed-in user's folder.
insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values ('avatars', 'avatars', false, 2097152, array['image/jpeg', 'image/png', 'image/webp'])
on conflict (id) do nothing;

create policy "users read own avatar" on storage.objects
  for select to authenticated using (
    bucket_id = 'avatars' and (
      (storage.foldername(name))[1] = auth.uid()::text or public.is_admin()
    )
  );
create policy "users upload own avatar" on storage.objects
  for insert to authenticated with check (
    bucket_id = 'avatars' and (storage.foldername(name))[1] = auth.uid()::text
  );
create policy "users update own avatar" on storage.objects
  for update to authenticated using (
    bucket_id = 'avatars' and (storage.foldername(name))[1] = auth.uid()::text
  ) with check (
    bucket_id = 'avatars' and (storage.foldername(name))[1] = auth.uid()::text
  );
create policy "users delete own avatar" on storage.objects
  for delete to authenticated using (
    bucket_id = 'avatars' and (storage.foldername(name))[1] = auth.uid()::text
  );

-- All signed-in users may browse the catalog; only admins may change it.
create policy "authenticated read programs" on public.programs
  for select to authenticated using (true);
create policy "admin manages programs" on public.programs
  for all to authenticated using (public.is_admin()) with check (public.is_admin());

create policy "authenticated read universities" on public.universities
  for select to authenticated using (true);
create policy "admin manages universities" on public.universities
  for all to authenticated using (public.is_admin()) with check (public.is_admin());

create policy "authenticated read program links" on public.program_universities
  for select to authenticated using (true);
create policy "admin manages program links" on public.program_universities
  for all to authenticated using (public.is_admin()) with check (public.is_admin());

-- Public login-page request. Unknown emails intentionally receive the same response.
create function public.request_admin_contact(submitted_email text)
returns void
language plpgsql
security definer set search_path = public, auth
as $$
declare
  normalized_email text := lower(trim(coalesce(submitted_email, '')));
  matched_profile_id uuid;
begin
  if length(normalized_email) < 3 or length(normalized_email) > 320 then
    raise exception 'Enter a valid username or email address';
  end if;

  if normalized_email like '%@%' then
    select profile.id into matched_profile_id
    from auth.users account
    join public.profiles profile on profile.id = account.id
    where lower(account.email) = normalized_email
    limit 1;
  else
    select profile.id into matched_profile_id
    from public.profiles profile
    where lower(profile.username) = normalized_email
    limit 1;

    if matched_profile_id is not null then
      select lower(account.email) into normalized_email
      from auth.users account
      where account.id = matched_profile_id;
    end if;
  end if;

  if matched_profile_id is not null then
    insert into public.admin_contact_requests (profile_id, requester_email)
    values (matched_profile_id, normalized_email)
    on conflict (profile_id) where status = 'open' do nothing;

    if found then
      insert into public.admin_notifications (type, student_id)
      values ('admin_contact_requested', matched_profile_id);
    end if;
  end if;
end;
$$;

create function public.resolve_admin_contact_request(target_request_id uuid)
returns void
language plpgsql
security definer set search_path = public
as $$
begin
  if not public.is_admin() then
    raise exception 'Only administrators can resolve contact requests';
  end if;

  update public.admin_contact_requests
  set status = 'resolved', resolved_at = now(), resolved_by = auth.uid()
  where id = target_request_id and status = 'open';
end;
$$;

revoke all on function public.request_admin_contact(text) from public;
revoke all on function public.resolve_admin_contact_request(uuid) from public;
grant execute on function public.request_admin_contact(text) to anon, authenticated;
grant execute on function public.resolve_admin_contact_request(uuid) to authenticated;
alter publication supabase_realtime add table public.admin_contact_requests;

create function public.update_own_admin_username(requested_username text)
returns text
language plpgsql
security definer set search_path = public
as $$
declare
  normalized_username text := lower(trim(coalesce(requested_username, '')));
begin
  if not public.is_admin() then
    raise exception 'Only administrators can update an administrator username';
  end if;
  if normalized_username !~ '^[a-z0-9][a-z0-9._-]{2,29}$' then
    raise exception 'Username must be 3-30 characters and use only letters, numbers, dots, underscores, or hyphens';
  end if;
  update public.profiles set username = normalized_username
  where id = auth.uid() and role = 'admin';
  return normalized_username;
exception when unique_violation then
  raise exception 'That username is already in use';
end;
$$;

revoke all on function public.update_own_admin_username(text) from public;
grant execute on function public.update_own_admin_username(text) to authenticated;

create function public.update_student_username(target_student_id uuid, requested_username text)
returns text
language plpgsql
security definer set search_path = public
as $$
declare
  normalized_username text := lower(trim(coalesce(requested_username, '')));
begin
  if not public.is_admin() then
    raise exception 'Only administrators can update student usernames';
  end if;
  if normalized_username !~ '^[a-z0-9][a-z0-9._-]{2,29}$' then
    raise exception 'Username must be 3-30 characters and use only letters, numbers, dots, underscores, or hyphens';
  end if;
  if not exists (select 1 from public.profiles where id = target_student_id and role = 'student') then
    raise exception 'Student account not found';
  end if;
  update public.profiles set username = normalized_username
  where id = target_student_id and role = 'student';
  return normalized_username;
exception when unique_violation then
  raise exception 'That username is already in use';
end;
$$;

revoke all on function public.update_student_username(uuid, text) from public;
grant execute on function public.update_student_username(uuid, text) to authenticated;

-- Used by the Admin > Student Management delete action. It also removes auth.users.
create function public.delete_student(target_user_id uuid)
returns void
language plpgsql
security definer set search_path = public, auth
as $$
begin
  if not public.is_admin() then
    raise exception 'Only administrators can delete student accounts';
  end if;

  if target_user_id = auth.uid() then
    raise exception 'Administrators cannot delete their own account';
  end if;

  if not exists (
    select 1 from public.profiles
    where id = target_user_id and role = 'student'
  ) then
    raise exception 'Student not found';
  end if;

  delete from auth.users where id = target_user_id;
end;
$$;

revoke all on function public.delete_student(uuid) from public;
grant execute on function public.delete_student(uuid) to authenticated;

-- Bootstrap the first administrator after creating an account in Supabase Auth.
-- Replace the UUID with that user's id from Authentication > Users, then run:
-- update public.profiles set role = 'admin', status = 'approved'
-- where id = '00000000-0000-0000-0000-000000000000';
