-- Ledger of approval/rejection emails actually delivered to students.
-- Run once in the Supabase SQL Editor after schema.sql.
--
-- The unique (student_id, status) pair makes notification idempotent: approving
-- an already-approved student cannot send a second email, and a send that failed
-- (for example because no mail provider key is configured yet) leaves no row, so
-- it can be retried later.

begin;

create table if not exists public.student_status_emails (
  id bigint generated by default as identity primary key,
  student_id uuid not null references public.profiles(id) on delete cascade,
  status text not null check (status in ('approved', 'rejected')),
  recipient text not null,
  sent_at timestamptz not null default now(),
  unique (student_id, status)
);

create index if not exists student_status_emails_student_idx
  on public.student_status_emails (student_id, sent_at desc);

alter table public.student_status_emails enable row level security;

-- Administrators may review what was sent. Rows are written only by the
-- notify-student-status Edge Function using the service role, so no insert,
-- update, or delete policy is granted to clients.
drop policy if exists "admins read student status emails" on public.student_status_emails;
create policy "admins read student status emails" on public.student_status_emails
  for select using (public.is_admin());

commit;
